# -*- coding: utf-8 -*-
"""daypack.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HI12jTLGb4b-yyPkUjkVfaY0NvY-nSWq
"""

# 1. 필요한 패키지 설치
!pip install playwright pandas openpyxl
!playwright install chromium
!playwright install-deps

# 2. 크롤링 코드
import asyncio
import random
import urllib.parse
from datetime import datetime
import pandas as pd
from playwright.async_api import async_playwright
from google.colab import files
import re

MY_BRAND_KEYWORDS = ["데이팩", "daypack", "day pack"]

def is_my_brand(text: str) -> bool:
    """텍스트에 내 브랜드가 포함되어 있는지 확인"""
    if not text:
        return False
    text_lower = text.lower()
    return any(brand.lower() in text_lower for brand in MY_BRAND_KEYWORDS)

async def crawl_powerlink_mobile(page, keyword: str):
    """모바일 페이지에서 파워링크 크롤링"""

    print(f"  📌 파워링크 수집 중...")
    results = []

    try:
        powerlink_body = page.locator('xpath=//*[@id="power_link_body"]')

        if await powerlink_body.count() == 0:
            print("    → 파워링크 영역 없음")
            return results

        print(f"    ✓ 파워링크 영역 발견")

        items = powerlink_body.locator('li')
        item_count = await items.count()

        print(f"    → {item_count}개 파워링크 항목")

        for idx in range(item_count):
            try:
                li_item = items.nth(idx)

                # 브랜드명 추출
                brand_name = None
                landing_url = None

                span_paths = [
                    './/div/div[1]/div/a/div[1]/div/span[2]',
                    './/div/div[1]/div/a/div[1]/div/span[3]',
                    './/div/div[1]/div/a/div[1]/div/span[1]'
                ]

                for span_path in span_paths:
                    try:
                        span_elem = li_item.locator(f'xpath={span_path}')
                        if await span_elem.count() > 0:
                            text = await span_elem.first.inner_text()
                            text = text.strip()

                            if text and 2 <= len(text) <= 50:
                                brand_name = text
                                break
                    except:
                        continue

                # URL
                try:
                    link = li_item.locator('a').first
                    if await link.count() > 0:
                        landing_url = await link.get_attribute("href")
                except:
                    pass

                if brand_name and not is_my_brand(brand_name):
                    results.append({
                        "keyword": keyword,
                        "company": brand_name,
                        "product_name": "",
                        "url": landing_url or "",
                        "ad_type": "파워링크"
                    })
                    print(f"      {len(results)}위 - {brand_name}")
                elif brand_name and is_my_brand(brand_name):
                    print(f"      내 브랜드 (제외) - {brand_name}")

            except Exception as e:
                continue

    except Exception as e:
        print(f"  ⚠️ 파워링크 수집 실패: {e}")

    return results

async def crawl_shopping_ads_mobile(page, keyword: str, max_pages: int = 3):
    """네이버 쇼핑검색 광고 크롤링 - 상품 상세페이지 URL 수집"""

    print(f"  🛒 네이버 쇼핑검색 광고 수집 중 (최대 {max_pages}페이지)...")
    results = []

    try:
        # 1단계: 쇼핑 영역 찾기
        await asyncio.sleep(3)

        shopping_section = None

        # 방법 1: "네이버 가격비교" 텍스트로 찾기
        price_text_locator = page.locator("text=네이버 가격비교")
        if await price_text_locator.count() > 0:
            shopping_section = price_text_locator.locator('xpath=ancestor::section').first
            print("    ✓ 방법1: '네이버 가격비교' 텍스트로 영역 발견")

        # 방법 2: "쇼핑" 텍스트로 찾기
        if not shopping_section or await shopping_section.count() == 0:
            shopping_text = page.locator("text=쇼핑")
            if await shopping_text.count() > 0:
                shopping_section = shopping_text.locator('xpath=ancestor::section').first
                print("    ✓ 방법2: '쇼핑' 텍스트로 영역 발견")

        # 방법 3: 특정 클래스나 ID로 찾기
        if not shopping_section or await shopping_section.count() == 0:
            shopping_section = page.locator('section:has-text("가격비교"), section:has-text("쇼핑")').first
            if await shopping_section.count() > 0:
                print("    ✓ 방법3: has-text 선택자로 영역 발견")

        if not shopping_section or await shopping_section.count() == 0:
            print("    → 쇼핑 영역을 찾을 수 없음")
            return results

        collected_items = set()  # 중복 방지 (URL 기준)

        for page_num in range(max_pages):
            print(f"\n    📄 페이지 {page_num + 1}/{max_pages} 수집 시작")

            # 페이지 로딩 대기
            await asyncio.sleep(3)

            try:
                # 2단계: 광고 컨테이너 찾기 (div.Kq71T464.MAag3CXz)
                ad_containers = shopping_section.locator('div.Kq71T464.MAag3CXz')
                container_count = await ad_containers.count()
                print(f"       총 {container_count}개 광고 컨테이너 발견")

                ad_found_in_page = 0

                for idx in range(container_count):
                    try:
                        container = ad_containers.nth(idx)

                        # 디버깅 (처음 5개만)
                        if idx < 5:
                            print(f"\n       [디버그 {idx+1}] 광고 컨테이너 처리 중")

                        # 3단계: "광고" 텍스트 확인 (div > div)
                        ad_text_element = container.locator('div > div')

                        if await ad_text_element.count() == 0:
                            if idx < 5:
                                print(f"       → 광고 텍스트 요소 없음 (제외)")
                            continue

                        ad_text = await ad_text_element.first.inner_text()
                        ad_text = ad_text.strip()

                        if '광고' not in ad_text:
                            if idx < 5:
                                print(f"       → '광고' 텍스트 없음: '{ad_text}' (제외)")
                            continue

                        if idx < 5:
                            print(f"       ✓ '광고' 텍스트 확인")

                        # 4단계: 브랜드명 추출 (div > span)
                        brand_element = container.locator('div > span')

                        if await brand_element.count() == 0:
                            if idx < 5:
                                print(f"       → 브랜드명 요소 없음 (제외)")
                            continue

                        brand_name = await brand_element.first.inner_text()
                        brand_name = brand_name.strip()

                        if not brand_name or len(brand_name) < 2:
                            if idx < 5:
                                print(f"       → 브랜드명 너무 짧음 (제외)")
                            continue

                        if idx < 5:
                            print(f"       브랜드명: '{brand_name}'")

                        # 5단계: 데이팩 브랜드인지 확인
                        if is_my_brand(brand_name):
                            if idx < 5:
                                print(f"       → 데이팩 브랜드 (제외)")
                            continue

                        # 6단계: 부모 카드 찾기 (view_type_guide_로 시작하는 div)
                        parent_card = container.locator('xpath=ancestor::div[contains(@id, "view_type_guide_")]').first

                        if await parent_card.count() == 0:
                            if idx < 5:
                                print(f"       → 부모 카드 없음 (제외)")
                            continue

                        # 7단계: 상품명 추출 (strong)
                        product_element = parent_card.locator('strong')
                        product_name = ""

                        if await product_element.count() > 0:
                            product_name = await product_element.first.inner_text()
                            product_name = product_name.strip()

                        if idx < 5:
                            print(f"       상품명: '{product_name[:50] if product_name else '없음'}...'")

                        # 8단계: 상품 상세페이지 URL 추출
                        # 부모 카드 내에서 div > a 링크 찾기 (상품 이미지/제목 링크)
                        product_url = None

                        # 방법 1: 부모 카드의 li 내부에서 div > a 찾기
                        parent_li = container.locator('xpath=ancestor::li').first
                        if await parent_li.count() > 0:
                            product_link = parent_li.locator('div > a').first
                            if await product_link.count() > 0:
                                product_url = await product_link.get_attribute('href')
                                if idx < 5:
                                    print(f"       URL (방법1 - li > div > a): {product_url[:80] if product_url else 'None'}...")

                        # 방법 2: 부모 카드에서 직접 a 태그 찾기 (광고 마크가 아닌 것)
                        if not product_url:
                            all_links = parent_card.locator('a')
                            link_count = await all_links.count()

                            for link_idx in range(link_count):
                                temp_link = all_links.nth(link_idx)
                                temp_url = await temp_link.get_attribute('href')

                                # 광고 마크 링크가 아닌 상품 링크 찾기
                                # (shopping.naver.com 포함하거나 상대 경로)
                                if temp_url and ('shopping.naver.com' in temp_url or temp_url.startswith('/')):
                                    # 광고 마크 링크 제외 (부모가 광고 컨테이너인지 확인)
                                    link_parent = temp_link.locator('xpath=..')
                                    parent_class = await link_parent.get_attribute('class') if await link_parent.count() > 0 else ""

                                    if 'MAag3CXz' not in str(parent_class):
                                        product_url = temp_url
                                        if idx < 5:
                                            print(f"       URL (방법2 - 상품 링크): {product_url[:80]}...")
                                        break

                        # 방법 3: strong 태그의 부모 a 태그
                        if not product_url and product_element and await product_element.count() > 0:
                            strong_parent = product_element.locator('xpath=ancestor::a').first
                            if await strong_parent.count() > 0:
                                product_url = await strong_parent.get_attribute('href')
                                if idx < 5:
                                    print(f"       URL (방법3 - strong 부모): {product_url[:80] if product_url else 'None'}...")

                        if not product_url:
                            if idx < 5:
                                print(f"       → URL 추출 실패 (제외)")
                            continue

                        # URL 중복 확인
                        if product_url in collected_items:
                            if idx < 5:
                                print(f"       → 중복 URL (제외)")
                            continue

                        # URL 정규화
                        if not product_url.startswith('http'):
                            product_url = 'https://m.search.naver.com' + product_url

                        collected_items.add(product_url)

                        # 9단계: 저장
                        results.append({
                            "keyword": keyword,
                            "company": brand_name,
                            "product_name": product_name,
                            "url": product_url,
                            "ad_type": "쇼핑광고"
                        })
                        ad_found_in_page += 1
                        print(f"       ✓ {len(results)}위 - {brand_name} / {product_name[:30] if product_name else '상품명 없음'}...")

                    except Exception as e:
                        if idx < 5:
                            print(f"       [오류 {idx+1}] {str(e)[:100]}")
                        continue

                print(f"\n       → 이 페이지에서 {ad_found_in_page}개 광고 수집")

                # 10단계: 다음 페이지로 이동
                if page_num < max_pages - 1:
                    print(f"       다음 페이지 버튼 찾는 중...")

                    next_clicked = False

                    # 방법 1: aria-label로 찾기
                    next_button = shopping_section.locator('button[aria-label*="다음"], button[aria-label*="next"]').first
                    if await next_button.count() > 0 and await next_button.is_visible():
                        try:
                            await next_button.click()
                            next_clicked = True
                            print(f"       ✓ 방법1: aria-label로 다음 버튼 클릭")
                        except:
                            pass

                    # 방법 2: SVG 아이콘이 있는 버튼 중 오른쪽 것
                    if not next_clicked:
                        buttons = shopping_section.locator('button:has(svg)')
                        btn_count = await buttons.count()

                        for b_idx in range(btn_count):
                            try:
                                button = buttons.nth(b_idx)
                                if await button.is_visible():
                                    box = await button.bounding_box()
                                    if box and box['x'] > 187:
                                        await button.click()
                                        next_clicked = True
                                        print(f"       ✓ 방법2: 위치 기반으로 다음 버튼 클릭")
                                        break
                            except:
                                continue

                    # 방법 3: 텍스트로 찾기
                    if not next_clicked:
                        next_text_button = shopping_section.locator('button:has-text("다음")').first
                        if await next_text_button.count() > 0:
                            try:
                                await next_text_button.click()
                                next_clicked = True
                                print(f"       ✓ 방법3: 텍스트로 다음 버튼 클릭")
                            except:
                                pass

                    if next_clicked:
                        await asyncio.sleep(4 + random.uniform(1.0, 2.0))
                    else:
                        print(f"       → 다음 버튼을 찾을 수 없음 (마지막 페이지)")
                        break

            except Exception as e:
                print(f"    ⚠️ 페이지 {page_num + 1} 처리 중 오류: {e}")
                break

    except Exception as e:
        print(f"  ⚠️ 쇼핑 광고 수집 실패: {e}")

    return results

async def crawl_keyword(page, keyword: str):
    """하나의 모바일 페이지에서 파워링크와 쇼핑광고 크롤링"""

    encoded_keyword = urllib.parse.quote(keyword)
    url = f"https://m.search.naver.com/search.naver?query={encoded_keyword}"

    print(f"  🔗 URL: {url}")

    try:
        await page.goto(url, wait_until="networkidle", timeout=60000)
        await asyncio.sleep(6 + random.uniform(2, 3))
    except Exception as e:
        print(f"  ⚠️ 페이지 로딩 실패: {e}")
        return [], []

    # 1. 파워링크
    powerlink_results = await crawl_powerlink_mobile(page, keyword)

    await asyncio.sleep(2)

    # 2. 쇼핑 광고
    shopping_results = await crawl_shopping_ads_mobile(page, keyword, max_pages=3)

    return powerlink_results, shopping_results

def format_complaint_text(df):
    """네이버 신고용 텍스트 포맷 생성"""

    keywords_with_ads = df['keyword'].unique()

    if len(keywords_with_ads) == 0:
        return "경쟁사 광고가 발견된 키워드가 없습니다."

    keyword_list = ', '.join(keywords_with_ads)

    complaint_text = f"담당자님 안녕하세요, 브랜드키워드({keyword_list})에서 관련 없는 경쟁사 광고 노출 확인되어 노출제재 요청드립니다. 확인 부탁드립니다.\n\n"

    for _, row in df.iterrows():
        complaint_text += f"키워드: {row['keyword']}\n"
        complaint_text += f"업체명: {row['company']}\n"
        if row['product_name']:
            complaint_text += f"상품명: {row['product_name']}\n"
        complaint_text += f"URL: {row['url']}\n\n"

    return complaint_text

async def main():
    keywords = [
        '데이팩',
        '데이팩올인원',
        '데이팩올인원영양제','데이팩영양제','데이팩종합영양제','데이팩멀티비타민','데이팩종합비타민'
    ]

    print(f"\n{'='*70}")
    print(f"🔍 네이버 모바일 광고 모니터링 (상품 상세페이지 URL)")
    print(f"{'='*70}\n")

    all_results = []

    async with async_playwright() as p:
        browser = await p.chromium.launch(
            headless=True,
            args=[
                '--disable-blink-features=AutomationControlled',
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage'
            ]
        )

        context = await browser.new_context(
            locale="ko-KR",
            timezone_id="Asia/Seoul",
            viewport={"width": 375, "height": 812},
            user_agent="Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Mobile/15E148 Safari/604.1",
            device_scale_factor=3,
            is_mobile=True,
            has_touch=True
        )

        await context.add_init_script("""
            Object.defineProperty(navigator, 'webdriver', {get: () => undefined});
        """)

        page = await context.new_page()

        for idx, kw in enumerate(keywords, 1):
            print(f"\n{'='*70}")
            print(f"[{idx}/{len(keywords)}] 키워드: '{kw}'")
            print(f"{'='*70}")

            powerlink_results, shopping_results = await crawl_keyword(page, kw)
            all_results.extend(powerlink_results)
            all_results.extend(shopping_results)

            if idx < len(keywords):
                wait_time = random.uniform(10, 15)
                print(f"\n⏳ {wait_time:.1f}초 대기...")
                await asyncio.sleep(wait_time)

        await browser.close()

    # 결과 저장
    if all_results:
        df = pd.DataFrame(all_results)
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')

        excel_file = f"naver_ads_{timestamp}.xlsx"
        with pd.ExcelWriter(excel_file, engine='openpyxl') as writer:
            df.to_excel(writer, sheet_name='전체', index=False)

            powerlink_df = df[df['ad_type'] == '파워링크']
            if len(powerlink_df) > 0:
                powerlink_df.to_excel(writer, sheet_name='파워링크', index=False)

            shopping_df = df[df['ad_type'] == '쇼핑광고']
            if len(shopping_df) > 0:
                shopping_df.to_excel(writer, sheet_name='쇼핑광고', index=False)

        complaint_text = format_complaint_text(df)
        txt_file = f"complaint_text_{timestamp}.txt"
        with open(txt_file, 'w', encoding='utf-8') as f:
            f.write(complaint_text)

        complaint_df = df[['keyword', 'company', 'product_name', 'url']].copy()
        complaint_excel = f"complaint_format_{timestamp}.xlsx"
        complaint_df.to_excel(complaint_excel, index=False)

        print("\n" + "="*70)
        print("📊 수집 결과")
        print("="*70)

        keywords_with_ads = df['keyword'].unique()
        print(f"\n🎯 경쟁사 광고가 발견된 키워드 ({len(keywords_with_ads)}개):")
        print(f"   {', '.join(keywords_with_ads)}")

        keywords_without_ads = [kw for kw in keywords if kw not in keywords_with_ads]
        if keywords_without_ads:
            print(f"\n✅ 경쟁사 광고가 없는 키워드 ({len(keywords_without_ads)}개):")
            print(f"   {', '.join(keywords_without_ads)}")

        print("\n" + "="*70)
        print("📈 광고 유형별 통계")
        print("="*70)
        print(f"   파워링크: {len(df[df['ad_type'] == '파워링크'])}개")
        print(f"   쇼핑광고: {len(df[df['ad_type'] == '쇼핑광고'])}개")
        print(f"   총합: {len(df)}개")

        print("\n" + "="*70)
        for kw in keywords_with_ads:
            kw_data = df[df['keyword'] == kw]
            if len(kw_data) > 0:
                print(f"\n🔑 키워드: '{kw}' ({len(kw_data)}개)")
                for _, row in kw_data.iterrows():
                    if row['product_name']:
                        print(f"  - [{row['ad_type']}] {row['company']} / {row['product_name'][:40]}")
                    else:
                        print(f"  - [{row['ad_type']}] {row['company']}")

        print("\n" + "="*70)
        print("📝 신고용 텍스트")
        print("="*70)
        print(complaint_text)

        print("\n" + "="*70)
        print("✅ 파일 저장 완료")
        print(f"   1. {excel_file} - 원본 데이터")
        print(f"   2. {complaint_excel} - 신고용 포맷")
        print(f"   3. {txt_file} - 신고용 텍스트")
        print("="*70)

        files.download(excel_file)
        files.download(complaint_excel)
        files.download(txt_file)

    else:
        print("\n⚠️ 수집된 데이터 없음")
        print("모든 키워드에서 경쟁사 광고가 발견되지 않았습니다.")

# 실행
await main()